/**
 * Guards the hand-added `session_artifacts` block in database.types.ts.
 *
 * That file is normally generated by `npm run generate:db-types`, but this
 * work item's migration is deliberately not applied (per the operator's
 * instruction), so nothing regenerated it. A hand edit to a generated file
 * drifts from what generation would have produced with nothing to catch it —
 * this test is that catch, checked against both the migration SQL and the
 * TypeScript as text, so it does not need a running database.
 */
import { readFileSync } from "node:fs";
import { join } from "node:path";

import { describe, expect, it } from "vitest";

const migrationPath = join(
  process.cwd(),
  "supabase/migrations/20260910000000_add_session_artifacts.sql",
);
// The schema is two files now: the base `create table` and the alterations
// that widen it for spec artifacts. Never edit the base file to add a
// column — see that alter migration's own docblock for why (another
// session's database may already have run it, and this test pins its text
// by path).
const alterMigrationPath = join(
  process.cwd(),
  "supabase/migrations/20260911000000_add_spec_artifacts.sql",
);
const typesPath = join(process.cwd(), "src/types/database.types.ts");

const migration = readFileSync(migrationPath, "utf8");
const alterMigration = readFileSync(alterMigrationPath, "utf8");
const types = readFileSync(typesPath, "utf8");

/** The `session_artifacts` block, isolated from the rest of database.types.ts. */
function extractTypesBlock(): string {
  const start = types.indexOf("session_artifacts: {");
  expect(start, "session_artifacts block not found in database.types.ts").toBeGreaterThan(-1);
  // The block ends at the next top-level table key at the same indentation
  // (six spaces), which for this file is "session_projects: {".
  const end = types.indexOf("session_projects: {", start);
  expect(end, "session_projects block not found after session_artifacts").toBeGreaterThan(start);
  return types.slice(start, end);
}

/** Column name -> { notNull, hasDefault } as declared in the `create table`. */
function parseMigrationColumns(): Map<string, { notNull: boolean; hasDefault: boolean }> {
  const tableMatch = /create table public\.session_artifacts \(([\s\S]*?)\n\);/.exec(migration);
  expect(tableMatch, "create table public.session_artifacts not found").not.toBeNull();
  const body = tableMatch![1]!;

  const columns = new Map<string, { notNull: boolean; hasDefault: boolean }>();
  for (const rawLine of body.split("\n")) {
    const line = rawLine.trim();
    if (line.length === 0 || line.startsWith("--")) continue;
    // Skip constraint lines, which do not declare a column.
    if (/^constraint\b/i.test(line)) continue;

    const columnMatch = /^([a-z_]+)\s+/i.exec(line);
    if (!columnMatch) continue;
    const name = columnMatch[1]!;
    // `id` is the only column that is also a bare SQL keyword-shaped token
    // preceding "uuid primary key" etc.; every real column line here starts
    // with `<name> <type>`, so this is safe.
    if (!/^(id|session_id|artifact_key|kind|attribution|tool_call_id|tool_name|round_id|project_path|payload|created_at|turn_id)$/.test(name)) {
      continue;
    }

    columns.set(name, {
      hasDefault: /\bdefault\b/i.test(line),
      notNull: /\bnot null\b/i.test(line) || name === "id",
    });
  }
  return columns;
}

/**
 * Apply the alter migration's column-affecting statements on top of the base
 * migration's columns, in place, and return the same map.
 *
 * Recognises exactly two statement shapes and nothing else — an
 * `alter table` this does not recognise fails the test instead of being
 * silently ignored, which is the point: a schema-widening migration this
 * test cannot see is a schema-widening migration `database.types.ts` could
 * silently disagree with.
 */
function applyAlterations(
  columns: Map<string, { notNull: boolean; hasDefault: boolean }>,
  alterSql: string,
): Map<string, { notNull: boolean; hasDefault: boolean }> {
  const statements = alterSql
    .split(";")
    .map((s) => s.trim())
    .filter((s) => s.length > 0 && !s.startsWith("--"));

  for (const statement of statements) {
    // Strip leading comment lines within a statement (a statement can be
    // preceded by its own docblock lines that survived the naive `;` split).
    const body = statement
      .split("\n")
      .filter((line) => !line.trim().startsWith("--"))
      .join("\n")
      .trim();
    if (body.length === 0) continue;
    if (!/^alter table public\.session_artifacts\b/i.test(body)) continue;

    const addColumn = /^alter table public\.session_artifacts\s+add column\s+([a-z_]+)\s+([a-z]+)/i.exec(
      body,
    );
    if (addColumn) {
      const [, name] = addColumn;
      columns.set(name!, { hasDefault: false, notNull: false });
      continue;
    }

    const dropNotNull = /^alter table public\.session_artifacts\s+alter column\s+([a-z_]+)\s+drop not null/i.exec(
      body,
    );
    if (dropNotNull) {
      const [, name] = dropNotNull;
      const existing = columns.get(name!);
      expect(existing, `alter column ${name} refers to an unknown column`).toBeDefined();
      columns.set(name!, { ...existing!, notNull: false });
      continue;
    }

    // add/drop constraint statements do not affect column shape and are
    // deliberately not recognised above; every other `alter table
    // session_artifacts` statement is an error in this test, not a silent
    // no-op.
    expect(
      /^alter table public\.session_artifacts\s+(add|drop) constraint\b/i.test(body),
      `unrecognised alter statement against session_artifacts: ${body}`,
    ).toBe(true);
  }

  return columns;
}

/** The `kind` values accepted by whichever migration declares the live check. */
function parseKindCheckValues(): string[] {
  const match = /check\s*\(\s*kind\s+in\s*\(([^)]+)\)\s*\)/i.exec(alterMigration);
  expect(match, "kind check constraint not found in the alter migration").not.toBeNull();
  return match![1]!
    .split(",")
    .map((s) => s.trim().replace(/^'|'$/g, ""));
}

describe("session_artifacts schema — migration vs. hand-added types", () => {
  const migrationColumns = applyAlterations(parseMigrationColumns(), alterMigration);
  const typesBlock = extractTypesBlock();

  it("declared every expected column across the base and alter migrations", () => {
    const expected = [
      "id",
      "session_id",
      "artifact_key",
      "kind",
      "attribution",
      "tool_call_id",
      "tool_name",
      "round_id",
      "project_path",
      "payload",
      "created_at",
      "turn_id",
    ];
    for (const column of expected) {
      expect(migrationColumns.has(column), `migration is missing column "${column}"`).toBe(true);
    }
    expect(migrationColumns.size).toBe(expected.length);
    expect(migrationColumns.size).toBe(12);
  });

  it("every migration column appears in Row, Insert and Update", () => {
    for (const column of migrationColumns.keys()) {
      const rowField = new RegExp(`^\\s*${column}:`, "m");
      expect(rowField.test(typesBlock), `Row is missing "${column}"`).toBe(true);

      const insertOrUpdateField = new RegExp(`^\\s*${column}\\??:`, "m");
      expect(insertOrUpdateField.test(typesBlock), `Insert/Update missing "${column}"`).toBe(
        true,
      );
    }
  });

  it("nullability in Row matches `not null` in the migration", () => {
    const rowSection = typesBlock.slice(
      typesBlock.indexOf("Row: {"),
      typesBlock.indexOf("Insert: {"),
    );

    for (const [column, { notNull }] of migrationColumns) {
      const fieldMatch = new RegExp(`^\\s*${column}:\\s*(.+)$`, "m").exec(rowSection);
      expect(fieldMatch, `Row field "${column}" not found`).not.toBeNull();
      const isNullable = /\|\s*null/.test(fieldMatch![1]!);
      expect(
        isNullable,
        `Row.${column} nullability disagrees with the migration (not null: ${String(notNull)})`,
      ).toBe(!notNull);
    }
  });

  it("a column with a default (or nullable) is optional in Insert", () => {
    const insertSection = typesBlock.slice(
      typesBlock.indexOf("Insert: {"),
      typesBlock.indexOf("Update: {"),
    );

    for (const [column, { hasDefault, notNull }] of migrationColumns) {
      const fieldMatch = new RegExp(`^\\s*${column}(\\??):`, "m").exec(insertSection);
      expect(fieldMatch, `Insert field "${column}" not found`).not.toBeNull();
      const isOptional = fieldMatch![1] === "?";
      const shouldBeOptional = hasDefault || !notNull;
      expect(
        isOptional,
        `Insert.${column} optionality disagrees with the migration (hasDefault: ${String(hasDefault)}, notNull: ${String(notNull)})`,
      ).toBe(shouldBeOptional);
    }
  });

  it("the foreign key relationship matches the migration's reference", () => {
    expect(migration).toMatch(
      /session_id uuid not null references public\.sessions\(id\) on delete cascade/,
    );
    expect(typesBlock).toContain('foreignKeyName: "session_artifacts_session_id_fkey"');
    expect(typesBlock).toContain('referencedRelation: "sessions"');
    expect(typesBlock).toContain('referencedColumns: ["id"]');
  });

  it("every `references` in the migration has a matching index or is the primary key", () => {
    // session_id is the only `references` in this migration, and it has its
    // own dedicated index in addition to the composite one — see the "Every
    // foreign key gets an index" comment in the migration itself.
    expect(migration).toMatch(/references public\.sessions\(id\)/);
    expect(migration).toContain(
      "create index session_artifacts_session_id_idx\n  on public.session_artifacts (session_id);",
    );
  });

  it("the kind check accepts exactly diff, commit, pr, spec", () => {
    expect(parseKindCheckValues()).toEqual(["diff", "commit", "pr", "spec"]);
  });

  it("requires project_path for every kind except spec", () => {
    expect(alterMigration).toContain("session_artifacts_project_path_required");
    expect(alterMigration).toMatch(
      /check\s*\(\s*kind\s*=\s*'spec'\s+or\s+project_path\s+is\s+not\s+null\s*\)/i,
    );
  });
});
